bl_info = {
    "name": "Zeros Shape Key Utils",
    "author": "Zeromaniac x ChatGPT",
    "version": (2, 0),
    "blender": (3, 6, 0),
    "location": "Shape Keys Context Menu",
    "description": "Adds more options to the shape key context menu.",
    "category": "Object",
    "support": "COMMUNITY",
    "warning": "",
    "wiki_url": "",
    "tracker_url": "",
    "version": (2, 0, 0),
    "ui": True,
    "icon": "PLUGIN",
    "license": "GPL-3.0",
    "author": "Zeromaniac x ChatGPT",
    "docs_url": "",
    "manual_url": "",
}